import Head from 'next/head'
import {Sidebar} from "../components/Sidebar";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Whatsapp v2</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <Sidebar />
      </main>
    </div>
  )
}
